# Generated by Django 4.1.5 on 2023-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('brand', models.TextField()),
                ('signatures', models.CharField(max_length=500)),
            ],
        ),
    ]
