# Generated by Django 4.1.5 on 2023-03-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='signatures',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
