# Generated by Django 4.1.5 on 2023-03-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_size_alter_product_id_colorsize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='BaseProduct',
        ),
        migrations.RenameModel(
            old_name='ColorSize',
            new_name='ColorSizeProduct',
        ),
    ]
