# Generated by Django 4.1.5 on 2023-03-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_colorsizeproduct_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsizeproduct',
            name='brand',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='colorsizeproduct',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
