# Generated by Django 4.1.5 on 2023-03-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_colorsizeproduct_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorSizeProduct',
            new_name='FinalProduct',
        ),
    ]
